services:
  mysql:
    image: mysql:latest
    container_name: teste_banco_dados_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: teste_banco_dados_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --local_infile=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 10s
      retries: 5
      timeout: 5s

  adminer:
    image: adminer:latest
    container_name: teste_banco_dados_db_adminer
    restart: always
    ports:
      - "8888:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql_data:
